name:                Day4
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/Day4#readme
license:             BSD-3-Clause
author:              Author name here
maintainer:          example@example.com
copyright:           2024 Author name here
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - cryptohash-md5
  - bytestring
  - utf8-string
  - base16-bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  Day4:
    source-dirs:      src
    main:             Main.hs
